server:
  port: 8401

spring:
  application:
    name: alibaba-payment-sentinel
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
        transport:
          dashboard: localhost:8080
          port: 8719

management: #暴露监控端点
  endpoints:
    web:
      exposure:
        include: "*"